export const NEW_MESSAGE_ALERT = "NEW_MESSAGE_ALERT";
export const NEW_MESSAGE = "NEW_MESSAGE";

export const MESSAGE_TYPING_START = "MESSAGE_TYPING_START";
export const MESSAGE_TYPING_STOP = "MESSAGE_TYPING_STOP";

export const NEW_REQUEST = "NEW_REQUEST";
